#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <inputfile> <num of reps> <groupname> <species>" 1>&2
    echo '   <inputfile>: Prefix of input matrix file' 1>&2
    echo '   <Ddir>: Directory of gene annotation files' 1>&2
    echo '   <num of reps>: Number of replicates (quated by ":")' 1>&2
    echo '   <group name>: Labels of two groups compared (quated by ":")' 1>&2
    echo '   <species>: [Human|Mouse|Rat|Fly|Celegans]' 1>&2
    echo '   Options:' 1>&2
    echo '      -t <float>: FDR threshould for DEG identification (default: 0.05)' 1>&2
    echo '      -n <int>: Number of top-ranked DEGs for GO analysis (default: 500)' 1>&2
    echo '      -k: Supply whe the input file is generated by "kallisto_merge.sh" (default: "rsem_merge.sh")' 1>&2
    echo "  Example:" 1>&2
    echo "   $cmdname Matrix 2:2 WT:KD Human" 1>&2
}

p=0.05
nGene_GO=500
kallisto="no"
while getopts t:n:k option
do
    case ${option} in
        t) p=${OPTARG};;
        n) nGene_GO=${OPTARG};;
        k) kallisto="yes";;
        *)
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 4 ]; then
  usage
  exit 1
fi

outname=$1
nrep=$2
gname=$3
sp=$4
n1=$(cut -d':' -f1 <<<${n})
n2=$(cut -d':' -f2 <<<${n})

if test $sp = "Human"; then
    orgdb=org.Hs.eg.db
    orggp=hsapiens
elif test $sp = "Mouse"; then
    orgdb=org.Mm.eg.db
    orggp=mmusculus
elif test $sp = "Rat"; then
    orgdb=org.Rn.eg.db
    orggp=rnorvegicus
elif test $sp = "Fly"; then
    orgdb=org.Dm.eg.db
    orggp=dmelanogaster
elif test $sp = "Celegans"; then
     orgdb=org.Ce.eg.db
     orggp=celegans
else
    echo "[Note] Species $sp is not included in [Human|Mouse|Rat|Fly|Celegans]. GO analysis will be skipped."
fi

Rdir=$(cd $(dirname $0) && pwd)
R="Rscript $Rdir/edgeR.R"

ex(){ echo $1; eval $1; }

create_xlsx(){
    post=$1
    for ty in DEGs upDEGs downDEGs; do
        head=$outname.$post.edgeR.$ty
        ncol=`head -n1 $head.tsv | awk '{print NF}'`
        n1=$((ncol-6))
        n2=$((ncol-5))
        n3=$((ncol-4))
        n4=$((ncol-3))
        n5=$((ncol-2))
        cut -f$n1,$n3,$n4 $head.tsv | grep -v chromosome > $head.bed
        grep -v chromosome $head.tsv | awk 'BEGIN { OFS="\t" } {print $'$n1', $'$n3', $'$n4', $2, $'$n5', $'$n2' }' > $head.bed6
    done
}

run_clusterProfiler(){
    ty=$1
    post=$2

    ifile=$outname.$post.edgeR.$ty.tsv
    n=`wc -l $ifile | cut -f1 -d " "`
    if test "$orgdb" != "" && test $n -gt 1; then
        Rscript $Rdir/run_clusterProfiler.R \
            -i=$ifile -n=$nGene_GO -orgdb=$orgdb \
            -o=$outname.$post.edgeR.GO.clusterProfiler.$ty \
            -tool=edger
    fi
}

if test $kallisto = "yes"; then
    echo "Execute the differential analysis for kallisto.."

    ### Gene
    for genetype in all pc; do
        postfix=genes.count.$genetype.annotated
        ex "$R -i=$outname.$postfix.tsv -n=$nrep -gname=$gname -o=$outname.$postfix -p=$p -nrowname=2 -ncolskip=1"

        create_xlsx $postfix
        s=""
        for ty in all DEGs upDEGs downDEGs; do
            head=$outname.$postfix.edgeR.$ty
            s="$s -i $head.tsv -n fitted-genes-$ty"
        done
        csv2xlsx.pl $s -o $outname.$postfix.edgeR.xlsx

        for ty in DEGs upDEGs downDEGs; do
            run_clusterProfiler $ty $postfix
        done
        if test "$orggp" != ""; then
            head=$outname.$postfix.edgeR
            n1=`wc -l $head.upDEGs.tsv | cut -f1 -d " "`
            n2=`wc -l $head.downDEGs.tsv | cut -f1 -d " "`
            if test $n1 -gt 1 && test $n2 -gt 1; then
            Rscript $Rdir/run_gprofiler2.R -i_up=$head.upDEGs.tsv -i_down=$head.downDEGs.tsv \
                    -n=$nGene_GO -org=$orggp -o=$head.GO.gProfiler2 \
                -tool=edger
            fi
        fi
    done

    ### Transcript
    postfix=transcript.count
    ex "$R -i=$outname.$postfix.tsv -n=$nrep -gname=$gname -o=$outname.$postfix -p=$p -nrowname=2 -ncolskip=1 -color=orange -noannotation"

    create_xlsx $postfix
    s=""
    for genetype in all DEGs upDEGs downDEGs; do
        s="$s -i outname.$postfix.edgeR.$genetype.tsv -n fitted-transcript-$genetype"
    done
    csv2xlsx.pl $s -o $outname.$postfix.edgeR.xlsx

else
    echo "Execute the differential analysis for RSEM.."
    postfix=count
    ex "$R -i=$outname.genes.$postfix.txt    -n=$nrep -gname=$gname -o=$outname.genes.$postfix    -p=$p -nrowname=2 -ncolskip=1"
    ex "$R -i=$outname.isoforms.$postfix.txt -n=$nrep -gname=$gname -o=$outname.isoforms.$postfix -p=$p -nrowname=2 -ncolskip=1 -color=orange"

    for genetype in genes isoforms; do
        create_xlsx $genetype.$postfix
        s=""
        for ty in all DEGs upDEGs downDEGs; do
            head=$outname.$genetype.$postfix.edgeR.$ty
            s="$s -i $head.tsv -n fitted-$genetype-$ty"
        done

        csv2xlsx.pl $s -o $outname.$genetype.$postfix.edgeR.xlsx
    done

    for genetype in DEGs upDEGs downDEGs; do
        run_clusterProfiler $genetype genes.$postfix
    done

    if test "$orggp" != ""; then
        head=$outname.genes.$postfix.edgeR
        n1=`wc -l $head.upDEGs.tsv   | cut -f1 -d " "`
        n2=`wc -l $head.downDEGs.tsv | cut -f1 -d " "`
        if test $n1 -gt 1 && test $n2 -gt 1; then
            Rscript $Rdir/run_gprofiler2.R -i_up=$head.upDEGs.tsv -i_down=$head.downDEGs.tsv \
                    -n=$nGene_GO -org=$orggp -o=$head.GO.gProfiler2 \
                    -tool=edger
        fi
    fi
fi