FROM rnakato/mapping:2023.04
LABEL maintainer="Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

USER root
WORKDIR /opt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    fastqc \
    libboost-all-dev \
    libbz2-dev \
    libcurl4-gnutls-dev \
    libgtkmm-3.0-dev \
    libgzstream0 \
    libgzstream-dev \
    liblzma-dev \
    libz-dev \
    cmake \
    curl \
    pigz \
    && apt-get clean \
    && rm -rf /var/lib/apt/list

RUN wget --progress=dot:giga https://github.com/alexdobin/STAR/archive/2.7.10a.tar.gz \
    && tar xzvf 2.7.10a.tar.gz \
    && cd STAR-2.7.10a/source \
    && make \
    && rm /opt/2.7.10a.tar.gz

RUN curl -s https://cloud.biohpc.swmed.edu/index.php/s/oTtGWbWjaxsQ2Ho/download > hisat2-2.2.1-Linux_x86_64.zip \
    && unzip hisat2-2.2.1-Linux_x86_64.zip \
    && rm hisat2-2.2.1-Linux_x86_64.zip

RUN wget --progress=dot:giga http://ccb.jhu.edu/software/stringtie/dl/stringtie-2.2.1.Linux_x86_64.tar.gz \
    && tar zxvf stringtie-2.2.1.Linux_x86_64.tar.gz \
    && rm /opt/stringtie-2.2.1.Linux_x86_64.tar.gz

RUN wget --progress=dot:giga https://github.com/deweylab/RSEM/archive/refs/tags/v1.3.3.tar.gz \
    && tar zxvf v1.3.3.tar.gz \
    && cd RSEM-1.3.3/ \
    && make \
    && rm /opt/v1.3.3.tar.gz

RUN wget --progress=dot:giga https://github.com/pachterlab/kallisto/releases/download/v0.46.1/kallisto_linux-v0.46.1.tar.gz \
    && tar zxvf kallisto_linux-v0.46.1.tar.gz \
    && R -e "devtools::install_github('pachterlab/sleuth')" \
    && rm kallisto_linux-v0.46.1.tar.gz

RUN wget --progress=dot:giga https://github.com/COMBINE-lab/salmon/releases/download/v1.8.0/salmon-1.8.0_linux_x86_64.tar.gz \
    && tar zxvf salmon-1.8.0_linux_x86_64.tar.gz \
    && rm salmon-1.8.0_linux_x86_64.tar.gz

RUN R -e "BiocManager::install(c('multtest', 'apeglm', 'limma', 'edgeR', 'DESeq2', 'Rtsne', 'tximport', 'tximportData', 'preprocessCore', 'rhdf5', 'ballgown', 'DEXSeq', 'GenomicFeatures', 'clusterProfiler', 'org.Mm.eg.db', 'org.Rn.eg.db', 'org.Hs.eg.db', 'org.Dm.eg.db', 'org.Ce.eg.db', 'AnnotationHub', 'enrichplot'))" \
    && R -e "install.packages(c('som','ggfortify','ggrepel','gplots','gprofiler2'))"

# MntJULiP
#RUN conda create -n mntjulip-env python=3.9 numpy scipy pandas Cython \
#    && source activate mntjulip-env \
#    && pip install --no-cache-dir "pystan<3" statsmodels "dask[complete]" \
#    && git clone https://github.com/splicebox/MntJULiP.git \
#    && cd MntJULiP \
#    && python setup.py install \
#    && conda deactivate \
# CHESSBOARD
RUN pip install --no-cache-dir git+https://bitbucket.org/biociphers/chessboard

COPY NCBI NCBI
COPY RumBall RumBall

ENV PATH ${PATH}:/opt/RSEM-1.3.3:/opt/STAR-2.7.10a/bin/Linux_x86_64:/opt/kallisto:/opt/salmon-1.8.0_linux_x86_64/bin/:/opt/hisat2-2.2.1:/opt/stringtie-2.2.1.Linux_x86_64:/opt/RumBall:/opt/ChIPseqTools/bin/

USER ubuntu
CMD ["/bin/bash", "-c"]